AllCops:
  # include gemspec and Rakefile
  Includes:
    - '**/*.gemspec'
    - '**/Rakefile'
    - 'tasks/**/*.rake'
  Excludes: []

# limit lines to 80 characters.
LineLength:
  Max: 80
  Enabled: true

# avoid methods longer than 30 lines of code
MethodLength:
  Max: 30
  CountComments: false
  Enabled: true

# avoid parameter lists longer than 5 parameters.
ParameterLists:
  Max: 5
  CountKeywordArgs: true
  Enabled: true

# don't prefer 'fail' over raise
SignalException:
  Description: 'Checks for proper usage of fail and raise.'
  Enabled: false

# disabled while we still support ruby 1.8
HashSyntax:
  Description: 'Prefer Ruby 1.9 hash syntax over 1.8 syntax'
  Enabled: false

# this doesn't work for things like port numbers
# we don't enforce this but please do it where it makes sense
NumericLiterals:
  Description: 'Add underscores to large numeric literals'
  Enabled: false

# we have some special exception types with error messages built in
RaiseArgs:
  Description: 'Checks the arguments passed to raise/fail.'
  Enabled: false

# used in the wire-protocol
ClassVars:
  Description: 'Avoid the use of class variables.'
  Enabled: false

# don't enforce arbitrary max class length
ClassLength:
  Description: 'Class length restriction'
  Enabled: false

# enforce UTF-8 Encoding for Ruby 1.9
Encoding:
  Enabled: false

# because ruby 1.8.x, that's why
DotPosition:
  Enabled: false
