---
name: MongoDB Ruby Driver
description: a pure-Ruby driver for connecting to, querying, and manipulating MongoDB databases
package: mongo
jira: https://jira.mongodb.org/projects/RUBY
version:
  number: 2.21.1
  file: lib/mongo/version.rb
