# Python toolchain as of this writing is available on rhel62, debian92 and
# ubuntu1604.
#
# To run rhel62 in docker, host system must be configured to emulate syscalls:
# https://github.com/CentOS/sig-cloud-instance-images/issues/103

<%

python_toolchain_url = "https://s3.amazonaws.com//mciuploads/mongo-python-driver-toolchain/#{distro}/ba92de2700c04ee2d4f82c3ffdfc33105140cb04/mongo_python_driver_toolchain_#{distro.gsub('-', '_')}_ba92de2700c04ee2d4f82c3ffdfc33105140cb04_19_11_14_15_33_33.tar.gz"
server_version = '4.3.3'
server_url = "http://downloads.10gen.com/linux/mongodb-linux-x86_64-enterprise-#{distro}-#{server_version}.tgz"
server_archive_basename = File.basename(server_url)
server_extracted_dir = server_archive_basename.sub(/\.(tar\.gz|tgz)$/, '')

toolchain_upper='f11598d091441ffc8d746aacfdc6c26741a3e629' 
toolchain_lower='5e46f2793e8e866f36eda2c5_20_02_14_19_18_18' 

ruby_toolchain_url = "https://s3.amazonaws.com//mciuploads/mongo-ruby-toolchain/#{distro}/#{toolchain_upper}/mongo_ruby_driver_toolchain_#{distro.gsub('-', '_')}_patch_#{toolchain_upper}_#{toolchain_lower}.tar.gz"

%>

FROM <%= base_image %>

# increment to force apt-get update to run
RUN echo 2

<% if debian? %>

  ENV DEBIAN_FRONTEND=noninteractive

  RUN apt-get update

  RUN apt-get install -y curl

  <% if preload? && distro =~ /ubuntu1204/ %>
  
    # ubuntu1204 comes with python 2.7.3.
    # Install a more recent one from deadsnakes ppa so that pip works.
    RUN apt-get install -y python-software-properties
    # https://github.com/deadsnakes/issues/issues/53
    RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5BB92C09DB82666C
    RUN add-apt-repository ppa:fkrull/deadsnakes-python2.7
    RUN apt-get update
    RUN apt-get install -y python2.7-dev

  <% end %>

<% end %>

<% if ruby_head? %>

  # To use current versions of mlaunch, Python 3.6+ is required.
  # Most distros ship with older Pythons, therefore we need to install
  # a newer Python from somewhere. This section installs the Python
  # toolhcain which comes with recent Pythons.
  # Alternatively, Ruby toolchain compiles its own copy of Python 3 but
  # this is currently incomplete in that on older distros with old OpenSSL,
  # the built Python has no ssl module and hence practically is unusable.
  # Currently Ruby driver uses mtools-legacy which supports Python 2,
  # avoiding this entire issue for the time being.

  #RUN curl --retry 3 -fL <%= python_toolchain_url %> -o python-toolchain.tar.gz
  #RUN tar -xC /opt -zf python-toolchain.tar.gz

<% end %>

<% if debian? %>

  # Ruby runtime dependencies: libyaml-0-2
  # Compiling ruby libraries: gcc make
  # JRuby: openjdk-8-jre
  # Server dependencies: libsnmp30 libcurl3
  # Determining OS we are running on: lsb-release
  # Kerberos testing: krb5-user
  # Installing mlaunch from git: git
  # ruby-head archive: bzip2
  # nio4r on JRuby: libgmp-dev
  #
  # We currently use Python 2-compatible version of mtools, which
  # is installable via pip (which uses Python 2). All of the MongoDB
  # distros have pip installed (but none as of this writing have pip3)
  # therefore install python-pip in all configurations here.

  # ubuntu1204, ubuntu1404 only have openjdk-7-jre
  <% unless %w(ubuntu1204 ubuntu1404).include?(distro) %>
    RUN apt-get install -y openjdk-8-jre
  <% end %>

  <% if %w(ubuntu1204).include?(distro) %>
    RUN apt-get install -y libsnmp15
  <% else %>
    RUN apt-get install -y libsnmp30
  <% end %>

  # ubuntu1204, ubuntu1404, ubuntu1604: libcurl3
  RUN apt-get install -y libyaml-0-2 gcc make git lsb-release libcurl3 \
    krb5-user bzip2 libgmp-dev python-pip

<% else %>

  # lsb_release: redhat-lsb-core
  # our runner scripts: which
  # Ruby dependency: libyaml
  # compiling python packages: gcc python-devel
  
  RUN yum install -y redhat-lsb-core which git gcc python-devel libyaml

<% end %>

<% if preload? %>

  WORKDIR /app

  RUN curl --retry 3 -fL <%= server_download_url %> -o <%= File.basename(server_download_url) %>
  RUN tar xfz <%= File.basename(server_download_url) %>
  RUN mv mongo*/ /opt/mongodb
  ENV USE_OPT_MONGODB=1
  
  <% unless ruby_head? %>
    
    RUN curl --retry 3 -fL <%= ruby_toolchain_url %> -o ruby-toolchain.tar.gz
    RUN tar -xC /opt -zf ruby-toolchain.tar.gz
    ENV PATH=/opt/rubies/<%= ruby %>/bin:$PATH
    #ENV PATH=/opt/rubies/python/3/bin:$PATH
    ENV USE_OPT_TOOLCHAIN=1
  
  <% end %>
  
  <% if distro =~ /ubuntu1204|rhel/ %>
  
    # Ubuntu 12.04 ships pip 1.0 which is ancient and does not work.
    # rhel apparently does not package pip at all in core repoitories,
    # therefore install it the manual way.
    # https://pip.pypa.io/en/stable/installing/
    RUN curl --retry 3 -fL https://bootstrap.pypa.io/get-pip.py | python
  
  <% end %>

  RUN pip --version
  
  RUN pip install mtools-legacy[mlaunch]

<% end %>

WORKDIR /app

<% if preload? && !ruby_head? %>

  COPY Gemfile .
  COPY gemfiles gemfiles
  COPY *.gemspec .
  COPY lib/mongo/version.rb lib/mongo/version.rb
  RUN bundle install

<% end %>

COPY . .

ENV MONGO_ORCHESTRATION_HOME=/tmpfs \
  PROJECT_DIRECTORY=/app

ENV <%= @env.map { |k, v| %Q`#{k}="#{v.gsub('"', "\\\"")}"` }.join(" \\\n  ") %>

<% if expose? %>

  <% 0.upto(num_exposed_ports-1) do |i| %>
    EXPOSE <%= 27017 + i %>
  <% end %>

<% end %>
