# Python toolchain as of this writing is available on rhel62, debian92 and
# ubuntu1604.
#
# To run rhel62 in docker, host system must be configured to emulate syscalls:
# https://github.com/CentOS/sig-cloud-instance-images/issues/103

<%

python_toolchain_url = "https://s3.amazonaws.com//mciuploads/mongo-python-driver-toolchain/#{distro}/ba92de2700c04ee2d4f82c3ffdfc33105140cb04/mongo_python_driver_toolchain_#{distro.gsub('-', '_')}_ba92de2700c04ee2d4f82c3ffdfc33105140cb04_19_11_14_15_33_33.tar.gz"
server_version = '4.3.3'
server_url = "http://downloads.10gen.com/linux/mongodb-linux-x86_64-enterprise-#{distro}-#{server_version}.tgz"
server_archive_basename = File.basename(server_url)
server_extracted_dir = server_archive_basename.sub(/\.(tar\.gz|tgz)$/, '')

toolchain_upper='717e3e0a26debdc100fecee0d093e488ee7a0219'

ruby_toolchain_url = "http://boxes.10gen.com/build/toolchain-drivers/mongo-ruby-driver/ruby-toolchain-#{distro}-#{toolchain_upper}.tar.xz"
#ruby_toolchain_url = "https://s3.amazonaws.com//mciuploads/mongo-ruby-toolchain/#{distro}/#{toolchain_upper}/mongo_ruby_driver_toolchain_#{distro.gsub('-', '_')}_patch_#{toolchain_upper}_#{toolchain_lower}.tar.gz"

%>

FROM <%= base_image %>

<% if debian? %>

  ENV DEBIAN_FRONTEND=noninteractive

  # increment the counter to force apt-get update to run.
  # zsh is not required for any scripts but it is a better interactive shell
  # than bash.
  RUN echo 2 && \
    apt-get update && \
    apt-get install -y curl zsh

<% end %>

<% if ruby_head? %>

  # To use current versions of mlaunch, Python 3.6+ is required.
  # Most distros ship with older Pythons, therefore we need to install
  # a newer Python from somewhere. This section installs the Python
  # toolhcain which comes with recent Pythons.
  # Alternatively, Ruby toolchain compiles its own copy of Python 3 but
  # this is currently incomplete in that on older distros with old OpenSSL,
  # the built Python has no ssl module and hence practically is unusable.
  # Currently Ruby driver uses mtools-legacy which supports Python 2,
  # avoiding this entire issue for the time being.

  #RUN curl --retry 3 -fL <%= python_toolchain_url %> -o python-toolchain.tar.gz
  #RUN tar -xC /opt -zf python-toolchain.tar.gz

<% end %>

<% if debian? %>

  # Ruby runtime dependencies: libyaml-0-2
  # Compiling ruby libraries: gcc make
  # Compiling pyhton packages: python2.7-dev
  # JRuby: openjdk-8-jre
  # Server dependencies: libsnmp30 libcurl3/libcurl4
  # Determining OS we are running on: lsb-release
  # Kerberos testing: krb5-user
  # Local Kerberos server: krb5-kdc krb5-admin-server
  # Installing mlaunch from git: git
  # ruby-head archive: bzip2
  # nio4r on JRuby: libgmp-dev
  #
  # We currently use Python 2-compatible version of mtools, which
  # is installable via pip (which uses Python 2). All of the MongoDB
  # distros have pip installed (but none as of this writing have pip3)
  # therefore install python-pip in all configurations here.

  # ubuntu1404 only has openjdk-7-jre
  <% if distro !~ /ubuntu1404/ %>
    RUN apt-get install -y openjdk-8-jre
  <% end %>
  
  # ubuntu1404, ubuntu1604: libcurl3
  # ubuntu1804: libcurl4
  <% if distro =~ /ubuntu1804/ %>
    RUN apt-get install -y libcurl4
  <% else %>
    RUN apt-get install -y libcurl3
  <% end %>

  RUN apt-get install -y libsnmp30 libyaml-0-2 gcc make git lsb-release \
    krb5-user krb5-kdc krb5-admin-server bzip2 libgmp-dev python-pip python2.7-dev

<% else %>

  # Enterprise server: net-snmp
  # lsb_release: redhat-lsb-core
  # our runner scripts: which
  # Ruby dependency: libyaml
  # compiling python packages: gcc python-devel
  # Kerberos tests: krb5-workstation + cyrus-sasl-devel to build the
  # mongo_kerberos gem + cyrus-sasl-gssapi for authentication to work
  # Local Kerberos server: krb5-server
  # JRuby: java-1.8.0-openjdk
  #
  # Note: lacking cyrus-sasl-gssapi produces a cryptic message
  # "SASL(-4): no mechanism available: No worthy mechs found"
  # https://github.com/farorm/python-ad/issues/10
  
  RUN yum install -y redhat-lsb-core which git gcc libyaml krb5-server \
    krb5-workstation cyrus-sasl-devel cyrus-sasl-gssapi java-1.8.0-openjdk \
    net-snmp
    
  <% if distro =~ /rhel6/ %>
    
    # RHEL 6 ships with Python 2.6.
    
    RUN yum install -y centos-release-scl && \
      yum install -y python27-python python27-python-devel
    ENV PATH=/opt/rh/python27/root/usr/bin:$PATH \
      LD_LIBRARY_PATH=/opt/rh/python27/root/usr/lib64
  
  <% else %>
    
    RUN yum install -y python-devel
  
  <% end %>

<% end %>

<% if preload? %>

  WORKDIR /app

  RUN curl --retry 3 -fL <%= server_download_url %> |tar xzf - && \
    mv mongo*/ /opt/mongodb
  ENV USE_OPT_MONGODB=1
  
  <% unless ruby_head? %>
    
    RUN curl --retry 3 -fL <%= ruby_toolchain_url %> |tar -xC /opt -Jf -
    ENV PATH=/opt/rubies/<%= ruby %>/bin:$PATH \
      USE_OPT_TOOLCHAIN=1
    #ENV PATH=/opt/rubies/python/3/bin:$PATH
  
  <% end %>
  
  <% if distro =~ /rhel|ubuntu1604/ %>
  
    # Ubuntu 12.04 ships pip 1.0 which is ancient and does not work.
    #
    # Ubuntu 16.04 apparently also ships a pip that does not work:
    # https://stackoverflow.com/questions/37495375/python-pip-install-throws-typeerror-unsupported-operand-types-for-retry
    # Potentially this only affects environments with less than ideal
    # connectivity (or, perhaps, when python package registry is experiencing
    # availability issues) when pip must retry to install packages.
    #
    # rhel apparently does not package pip at all in core repoitories,
    # therefore install it the manual way.
    #
    # https://pip.pypa.io/en/stable/installing/
    RUN curl --retry 3 -fL https://bootstrap.pypa.io/get-pip.py | python
  
  <% end %>

  RUN pip --version && \
    pip install mtools-legacy[mlaunch]

<% end %>

WORKDIR /app

<% if preload? && !ruby_head? %>

  COPY Gemfile .
  COPY gemfiles gemfiles
  COPY *.gemspec .
  COPY lib/mongo/version.rb lib/mongo/version.rb
  RUN bundle install

<% end %>

COPY . .

ENV MONGO_ORCHESTRATION_HOME=/tmpfs \
  PROJECT_DIRECTORY=/app

ENV <%= @env.map { |k, v| %Q`#{k}="#{v.gsub('$', "\\$").gsub('"', "\\\"")}"` }.join(" \\\n  ") %>

<% if expose? %>

  <% 0.upto(num_exposed_ports-1) do |i| %>
    EXPOSE <%= 27017 + i %>
  <% end %>

<% end %>
