#!/bin/sh

# Copies the current directory to the specified target, then runs the
# provision script on the target.
#
# The current directory is copied into the `work` subdirectory of the user's
# home directory on the target.
#
# The target is meant to be an EC2 instance which will be provisioned with the
# required software to be able to build and run a Docker container with the
# driver's test suite.

set -e

target="$1"
if test -z "$target"; then
  echo Usage: `basename $0` user@host 1>&2
  exit 1
fi

shift

method="$1"

. `dirname $0`/functions-remote.sh

do_ssh "$target" '
  if test `id -u` = 0; then
    apt-get update &&
    apt-get -y install rsync sudo
  else
    sudo apt-get update &&
    sudo apt-get -y install rsync
  fi
'

do_rsync --delete --exclude .git --exclude .env.private\* -av \
  --exclude gem-private_key.pem \
  . $target:work

if test "$method" = local; then
  script=provision-local
else
  script=provision-docker
fi

do_ssh "$target" "cd work && ./.evergreen/$script"
