#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), '_common.rb')
db = Mongo.new(DEFAULT_HOST, DEFAULT_PORT).db(DEFAULT_DB)
coll = db.collection('part1')

if $DEBUG
  coll.drop
end

100.times { |i| coll.insert('x' => i) }
