#!/usr/bin/env ruby

require File.join(File.dirname(__FILE__), '_common.rb')
db = Mongo.new(DEFAULT_HOST, DEFAULT_PORT).db(DEFAULT_DB)

if $DEBUG
  db.drop_collection('capped1')
  db.drop_collection('capped2')
end

db.create_collection('capped1', :capped => true, :size => 500)
coll = db.collection('capped1')
coll.insert('x' => 1)
coll.insert('x' => 2)

db.create_collection('capped2', :capped => true, :size => 1000, :max => 11)
coll = db.collection('capped2')
str = ''
100.times {
  coll.insert('dashes' => str)
  str << '-'
}
